// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PresenceFlow.Data;

#nullable disable

namespace PresenceFlow.Migrations
{
    [DbContext(typeof(PresenceDbContext))]
    partial class PresenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PresenceFlow.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthVersion")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("authVersion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("vorname");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("istAdmin");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("nachname");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("zustand");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("zeitstempel");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
